/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticlePage: typeof import('./src/components/indexCom/article/articlePage.vue')['default']
    Bread: typeof import('./src/components/indexCom/index/Bread.vue')['default']
    ClassifyPage: typeof import('./src/components/indexCom/classify/classifyPage.vue')['default']
    CommentPage: typeof import('./src/components/indexCom/comment/commentPage.vue')['default']
    CustomerSPage: typeof import('./src/components/indexCom/customerService/customerSPage.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElText: typeof import('element-plus/es')['ElText']
    ForgetPage: typeof import('./src/components/LoginCom/ForgetPage.vue')['default']
    HeaderPage: typeof import('./src/components/indexCom/index/headerPage.vue')['default']
    IndexPage: typeof import('./src/components/indexCom/index/indexPage.vue')['default']
    LoginPage: typeof import('./src/components/LoginCom/LoginPage.vue')['default']
    Menu: typeof import('./src/components/indexCom/index/Menu.vue')['default']
    PersonEditPage: typeof import('./src/components/indexCom/index/personEditPage.vue')['default']
    RegisterPage: typeof import('./src/components/LoginCom/RegisterPage.vue')['default']
    ResourcesPage: typeof import('./src/components/indexCom/resources/resourcesPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemPage: typeof import('./src/components/indexCom/system/SystemPage.vue')['default']
    TagPage: typeof import('./src/components/indexCom/tag/tagPage.vue')['default']
    UserEditPage: typeof import('./src/components/indexCom/user/userEditPage.vue')['default']
    UserInsertPage: typeof import('./src/components/indexCom/user/userInsertPage.vue')['default']
    UserPage: typeof import('./src/components/indexCom/user/userPage.vue')['default']
  }
}
